name: flutter_template
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  # delete all comments(#) after setting up your own packages
  # required --- Other files are using the packages
  # optional --- No effect after removed

  # icons #
  # required
  cupertino_icons: ^1.0.8
  # optional
  iconsax: ^0.0.8

  # generator #
  # required
  flutter_gen: ^5.8.0

  # state managements #
  # optional
  provider: ^6.1.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # utils #
  # required
  device_preview: ^1.2.0
  go_router: ^14.4.1
  flutter_spinkit: ^5.2.1
  http: ^1.2.2
  intl: ^0.19.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  dio: ^5.7.0
  dart_jsonwebtoken: ^2.14.1

  # storage #
  # required
  get_storage: ^2.1.1
  shared_preferences: ^2.3.3

  # widgets #
  # required
  fluttertoast: ^8.2.8
  # optional
  smooth_page_indicator: ^1.2.0+3
  skeletonizer: ^1.4.2
  flutter_platform_widgets: ^7.0.1
  flutter_native_splash: ^2.4.2
  google_nav_bar: ^5.0.7
  carousel_slider: ^5.0.0
  flutter_slidable: ^3.1.1
  otp_text_field: ^1.1.3
  country_code_picker: ^3.1.0

  # providers #
  # optional
  google_sign_in: ^6.2.2

  # animations #
  # optional
  animated_text_kit: ^4.2.2

  # firebase #
  # required
  firebase_core: ^3.7.0
  cloud_firestore: ^5.4.5
  firebase_auth: ^5.3.2
  firebase_storage: ^12.3.5
  firebase_app_check: ^0.3.1+5

  # json #
  # optional
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0

  # security #
  # required
  flutter_dotenv: ^5.2.1
  # optional
  permission_handler: ^11.3.1

  # connection #
  # required
  internet_connection_checker: ^1.0.0+1

  # resize #
  # optional
  responsive_framework: ^1.5.1
  resize: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

  # generator #
  # required
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  riverpod_generator: ^2.6.2
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.2

  # Config #
  # required
  flutter_launcher_icons: ^0.14.1
  change_app_package_name: ^1.4.0

# The following section is specific to flutter launcher icons packages.
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/logos/
    - assets/icons/
    - assets/fonts/
    - assets/gifs/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
